### ISSUE TITLE
bmfont and bmtext documentation missed

### ISSUE THREAD

**Issue by dmi7ry** [WebFreak001/D2DGame#1]
When I press to bmfont or bmtext on [site](http://d2d.webfreak.org), there is an error (404 Not Found). bmfont and bmtext appears when some other links pressed (for example, music)

**Comment by WebFreak001** [comment]
It's because I only had these modules for testing something and removed them before pushing but I generated the documentation before.

I planned on separating BMFont into a separate package (which I already did) and use that in D2DGame as TTF Font alternative

**Comment by WebFreak001** [comment]
Fixed
