### ISSUE TITLE
updating variable in toolkit.game

### ISSUE THREAD

**Issue by phebert5009** [WebFreak001/D2DGame#3]
the documentation for the start function says to use it to change the variables
(presumably _width, _height, _icon, _title, and _fps), which are private and do not have a write property.  
I would recommend having write property which throw exceptions after start for these variables.

**Comment by WebFreak001** [comment]
`windowWidth`, `windowHeight`, `windowIcon`, `windowTitle`, `maxFPS` are all `ref` properties, so they have getters & setters (and with `ref` also are usable with binary opOpEqualAssign operators like += or ~=). However be aware that you can not change these after the start function gets called (You have to override the start function and set them here), if you want to update them afterwards you have to access `window` and call member functions or overwrite the entire run function.

```d
class MyGame : Game
{
  public override void start()
  {
    windowTitle = "Hello D2DGame!";
    ...
  }

  ...
}
```
